# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-latest'
  strategy:
    matrix:
      Python381:
        python.version: '3.8'
        ONNX_PATH: onnx==1.12

      Python382:
        python.version: '3.8'
        ONNX_PATH: onnx==1.12

      Python391:
        python.version: '3.9'
        ONNX_PATH: onnx==1.12
  
      Python392:
        python.version: '3.9'
        ONNX_PATH: onnx==1.12

      Python393:
        python.version: '3.9'
        ONNX_PATH: onnx==1.14

      Python310_112:
        python.version: '3.10'
        ONNX_PATH: onnx==1.14


    maxParallel: 4

  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install 'protobuf==3.20.2'
      pip install pytest
    displayName: 'Install dependencies'

  - script: |
      pip install onnxruntime==1.15
      pip install onnxmltools
      pip install $(ONNX_PATH)
    displayName: 'Install onnxruntime, onnxmltools'

  # - script: |
  #     python -c "import onnxconverter_common"
  #   displayName: 'Check import without onnxruntime'

  - script: |
      pip install -e .
    displayName: 'Install onnxconverter_common'

  - script: |
      pip install flake8
      python -m flake8 onnxconverter_common
    displayName: 'run flake8 check'

  - script: |
      python -c "import onnxconverter_common"
      pytest tests --doctest-modules --junitxml=junit/test-results-onnxutils.xml
    displayName: 'pytest - onnxutils'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
