#################################################################################
#                               OneBranch Pipelines                             #
# This pipeline was created by EasyStart from a sample located at:              #
#   https://aka.ms/obpipelines/easystart/samples                                #
# Documentation:  https://aka.ms/obpipelines                                    #
# Yaml Schema:    https://aka.ms/obpipelines/yaml/schema                        #
# Retail Tasks:   https://aka.ms/obpipelines/tasks                              #
# Support:        https://aka.ms/onebranchsup                                   #
#################################################################################

trigger: none

variables:
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  LinuxContainerImage: 'centos:centos7' # Docker image which is used to build the project https://aka.ms/obpipelines/containers
  DEBIAN_FRONTEND: noninteractive

resources:
  repositories: 
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false # set to true to enable cloudvault
      runmode: stage # linux can run CloudVault upload as a separate stage
      dependsOn: linux_build
      artifacts:
        - drop_linux_stage_linux_job

    globalSdl: # https://aka.ms/obpipelines/sdl
      # tsa:
      #  enabled: true # SDL results of non-official builds aren't uploaded to TSA by default.
      # credscan:
      #   suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      policheck:
        break: true # always break the build on policheck issues. You can disable it by setting to 'false'
      # suppression:
      #   suppressionFile: $(Build.SourcesDirectory)\.gdn\global.gdnsuppress

    stages:
    - stage: firststage
      jobs:
      - job: Testjob
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(REPOROOT)\out'
          ob_sdl_binskim_break: true 

        steps:
        - script: sudo install -d -m 0777 /home/vsts/.conda/envs
          displayName: Fix Conda permissions

        - task: CondaEnvironment@1
          inputs:
            createCustomEnvironment: true
            environmentName: 'py3.9'
            packageSpecs: 'python=3.9'

        - script: |
            python -m pip install --upgrade pip
            conda config --set always_yes yes --set changeps1 no
            conda install -c conda-forge protobuf
            conda install -c conda-forge numpy
            pip install -r requirements.txt
            pip install onnxruntime
            pip install onnxmltools
            pip install onnx=-1.12.0
            pip install pytest
            pip install -e .
          displayName: 'Install dependencies'

        - script: |
            pip install flake8
            python -m flake8 onnxconverter_common
          displayName: 'run flake8 check'

        - script: |
            python -c "import onnxconverter_common"
            pytest tests --doctest-modules --junitxml=junit/test-results-onnxutils.xml
          displayName: 'pytest - onnxutils'

        - task: PublishTestResults@2
          inputs:
            testResultsFiles: '**/test-results.xml'
            testRunTitle: 'Python 3.9'
          condition: succeededOrFailed()
